#!/usr/bin/env bash
# Bootstrap Cursor → CloudWatch OTLP metrics for this project (WS9).
#
#   scripts/cursor_otel.sh              # install cursorscope + write ~/.cursorscope/.env
#   scripts/cursor_otel.sh --check      # verify token, ingestor health, OTLP probe
#
# Cursor has no native OTEL exporter (unlike Claude Code / Codex). This script
# configures cursorscope — a hook bridge — and relies on the project hooks in
# .cursor/hooks.json to forward Agent events to CloudWatch's managed OTLP
# metrics endpoint. Open this repo in Cursor and restart after running setup.
#
# Why a setup script rather than a launch wrapper:
#
#   Codex and Claude Code are CLIs — a wrapper can inject OTEL env/config at
#   exec time. Cursor is a GUI app with no first-party OTEL and no supported
#   otelHeadersHelper equivalent. The only supported extension point is hooks,
#   and cursorscope's ingestor reads its destination from ~/.cursorscope/.env.
#   Re-run this script when the CloudWatch bearer token rotates (~90 days).
#
# Signal scope: the metrics bearer token authenticates ONLY the CloudWatch OTLP
# metrics endpoint (same constraint as claude/codex — see build-notes/claude/
# 08-coding-agent-telemetry.md). cursorscope also emits traces and logs; those
# default to localhost:4318 and are expected to fail harmlessly here. Metrics
# are the signal this lab harvests for build-cost comparison.
#
# THIS PATH IS NOT YET PROVEN END TO END. Acceptance test: run setup, send one
# Agent turn in Cursor, then query CloudWatch for cursor_* / gen_ai.* series
# carrying @resource.tool=cursor (or service.name=cursor) before trusting it.
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CURSORSCOPE_HOME="${CURSORSCOPE_HOME:-$HOME/.cursorscope}"
MODE="${1:-setup}"

# Pin AWS_PROFILE from .env if the launching shell has none — same reason
# otel_headers.sh does: hook subprocesses are not the shell you configured.
if [ -z "${AWS_PROFILE:-}" ] && [ -f "$REPO/.env" ]; then
  AWS_PROFILE=$(grep -m1 '^AWS_PROFILE=' "$REPO/.env" | cut -d= -f2-)
  export AWS_PROFILE
fi

fetch_token() {
  local headers token
  headers=$("$REPO/scripts/otel_headers.sh")
  token=$(python3 -c '
import json, sys
try:
    auth = json.loads(sys.argv[1])["Authorization"]
except Exception:
    sys.exit(1)
print(auth.removeprefix("Bearer "))
' "$headers" 2>/dev/null)
  printf '%s' "${token:-}"
}

derive_project_repo() {
  local origin
  origin=$(git -C "$REPO" remote get-url origin 2>/dev/null || true)
  repo=$(printf '%s' "${origin%.git}" | awk -F'[:/]' 'NF>=2 {print $(NF-1)"/"$NF}')
  project="${repo##*/}"
  [ -z "${project:-}" ] && project=$(basename "$REPO")
  project="${project// /_}"
  repo="${repo// /_}"
}

build_attrs() {
  local project="$1" repo="$2" attrs="tool=cursor,project=${project}"
  [ -n "${repo:-}" ] && attrs="$attrs,repo=${repo}"
  [ -n "${A2ALAB_OTEL_EXTRA_ATTRS:-}" ] && attrs="$attrs,$A2ALAB_OTEL_EXTRA_ATTRS"
  printf '%s' "$attrs"
}

write_env() {
  local token="$1" project="$2" repo="$3" attrs="$4" endpoint
  endpoint="${A2ALAB_CW_OTLP_METRICS_ENDPOINT:-https://monitoring.us-east-1.amazonaws.com/v1/metrics}"
  mkdir -p "$CURSORSCOPE_HOME"
  cat >"$CURSORSCOPE_HOME/.env" <<EOF
# Generated by scripts/cursor_otel.sh — re-run when the CloudWatch token rotates.
PORT=4327
CURSORSCOPE_AUTO_START=true

# Metrics → CloudWatch managed OTLP (metrics-only bearer token).
OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=$endpoint
OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
OTEL_EXPORTER_OTLP_HEADERS=Authorization=Bearer $token

# Attribution — cursorscope maps service.* / deployment.environment to @resource.*
OTEL_SERVICE_NAME=cursor
OTEL_SERVICE_NAMESPACE=${project}
DEPLOYMENT_ENVIRONMENT=${repo:-${project}}
OTEL_RESOURCE_ATTRIBUTES=${attrs}

# Privacy — content-off posture (mirrors scripts/claude_otel.sh).
CURSOR_LOG_USER_PROMPTS=false
CURSOR_LOG_TOOL_DETAILS=false
CURSOR_MASK_USER_EMAIL=true

# Traces/logs are not exported to CloudWatch with the metrics token; leave
# defaults so cursorscope still runs (localhost export attempts fail quietly).
EOF
}

ensure_cursorscope() {
  if [ ! -f "$CURSORSCOPE_HOME/scripts/cursorscope-forward.sh" ]; then
    echo "cursor_otel: installing cursorscope to $CURSORSCOPE_HOME ..." >&2
    npx --yes @last9/cursorscope setup --no-hooks --yes --no-browser --home "$CURSORSCOPE_HOME"
  fi
}

restart_ingestor() {
  if [ -x "$CURSORSCOPE_HOME/scripts/stop-cursorscope.sh" ]; then
    "$CURSORSCOPE_HOME/scripts/stop-cursorscope.sh" 2>/dev/null || true
  fi
  if [ -x "$CURSORSCOPE_HOME/scripts/ensure-cursorscope.sh" ]; then
    CURSORSCOPE_HOME="$CURSORSCOPE_HOME" "$CURSORSCOPE_HOME/scripts/ensure-cursorscope.sh"
    local port="${PORT:-4327}" i
    for i in 1 2 3 4 5 6 7 8 9 10; do
      if curl -sf --max-time 1 "http://127.0.0.1:${port}/healthz" >/dev/null 2>&1; then
        return 0
      fi
      sleep 0.3
    done
    echo "cursor_otel: ingestor started but health check pending — see ~/.cursor/cursorscope.log" >&2
    return 0
  fi
  echo "cursor_otel: cursorscope ingestor scripts missing under $CURSORSCOPE_HOME" >&2
  return 1
}

run_check() {
  local token
  token=$(fetch_token)
  if [ -z "${token:-}" ]; then
    echo "cursor_otel --check: FAIL — no CloudWatch metrics token (aws sso login?)" >&2
    return 1
  fi
  echo "cursor_otel --check: token OK"

  if curl -sf --max-time 2 "http://127.0.0.1:${PORT:-4327}/healthz" >/dev/null 2>&1; then
    echo "cursor_otel --check: ingestor healthy on :${PORT:-4327}"
    if curl -sf --max-time 5 "http://127.0.0.1:${PORT:-4327}/debug/otlp-probe" 2>/dev/null; then
      echo
    fi
  else
    echo "cursor_otel --check: ingestor not running — run scripts/cursor_otel.sh first" >&2
    return 1
  fi

  if [ -f "$REPO/.cursor/hooks.json" ]; then
    echo "cursor_otel --check: project hooks present at .cursor/hooks.json"
  else
    echo "cursor_otel --check: WARN — missing .cursor/hooks.json in repo" >&2
  fi
  return 0
}

run_setup() {
  local token attrs
  token=$(fetch_token)
  if [ -z "${token:-}" ]; then
    who=$(aws sts get-caller-identity --query Account --output text 2>/dev/null || echo '<no AWS session>')
    echo "cursor_otel: no CloudWatch metrics token — unreadable as $who" >&2
    echo "cursor_otel: is the AWS session live? (aws sso login)" >&2
    exit 1
  fi

  derive_project_repo
  attrs=$(build_attrs "$project" "$repo")
  ensure_cursorscope
  write_env "$token" "$project" "$repo" "$attrs"
  restart_ingestor || true

  echo "cursor_otel: metrics → ${A2ALAB_CW_OTLP_METRICS_ENDPOINT:-https://monitoring.us-east-1.amazonaws.com/v1/metrics}" >&2
  echo "cursor_otel: resource attrs → $attrs" >&2
  echo "cursor_otel: cursorscope home → $CURSORSCOPE_HOME" >&2
  echo "cursor_otel: open this repo in Cursor, restart Cursor, send one Agent turn, then:" >&2
  echo "cursor_otel:   scripts/cursor_otel.sh --check" >&2
  echo "cursor_otel:   uv run python scripts/obs_harvest.py coding   # after datapoints land" >&2
}

case "$MODE" in
  --check|check)
    run_check
    ;;
  --help|-h|help)
    sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
    ;;
  setup|"")
    run_setup
    ;;
  *)
    echo "cursor_otel: unknown argument '$MODE' (try --check or --help)" >&2
    exit 1
    ;;
esac
