#!/usr/bin/env bash
# Bootstrap Kiro → CloudWatch OTLP metrics for this project (WS9).
#
#   scripts/kiro_otel.sh              # write .kiro/hooks/.env with token + endpoint
#   scripts/kiro_otel.sh --check      # verify token and hook config
#
# Kiro has no native OTEL exporter (same situation as Cursor). This script
# configures the .kiro/hooks/ forwarding layer: hooks fire on session, tool,
# file and prompt events, and forward.sh emits OTLP JSON directly to the
# CloudWatch managed metrics endpoint. No separate ingestor process (unlike
# Cursor's cursorscope) — each hook call is a single backgrounded curl.
#
# Signal scope: sessions, tool executions, file operations (saves/creates/
# deletes — the WS16 edit-acceptance signal), and prompts. Token/cost/model
# are NOT available from hooks (Probe 2 pending); those columns stay n/a.
#
# Re-run when the CloudWatch bearer token rotates (~90 days).
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODE="${1:-setup}"

# Pin AWS_PROFILE from .env if the launching shell has none.
if [ -z "${AWS_PROFILE:-}" ] && [ -f "$REPO/.env" ]; then
  AWS_PROFILE=$(grep -m1 '^AWS_PROFILE=' "$REPO/.env" | cut -d= -f2-)
  export AWS_PROFILE
fi

fetch_token() {
  local headers token
  headers=$("$REPO/scripts/otel_headers.sh")
  token=$(python3 -c '
import json, sys
try:
    auth = json.loads(sys.argv[1])["Authorization"]
except Exception:
    sys.exit(1)
print(auth.removeprefix("Bearer "))
' "$headers" 2>/dev/null)
  printf '%s' "${token:-}"
}

derive_project_repo() {
  local origin
  origin=$(git -C "$REPO" remote get-url origin 2>/dev/null || true)
  repo=$(printf '%s' "${origin%.git}" | awk -F'[:/]' 'NF>=2 {print $(NF-1)"/"$NF}')
  project="${repo##*/}"
  [ -z "${project:-}" ] && project=$(basename "$REPO")
  project="${project// /_}"
  repo="${repo// /_}"
}

write_env() {
  local token="$1" project="$2" repo="$3" endpoint
  endpoint="${A2ALAB_CW_OTLP_METRICS_ENDPOINT:-https://monitoring.us-east-1.amazonaws.com/v1/metrics}"
  cat >"$REPO/.kiro/hooks/.env" <<EOF
# Generated by scripts/kiro_otel.sh — re-run when the CloudWatch token rotates.
KIRO_OTLP_METRICS_ENDPOINT=$endpoint
KIRO_OTLP_METRICS_TOKEN=$token
KIRO_PROJECT=$project
KIRO_REPO=${repo:-${project}}
EOF
}

run_check() {
  local token
  token=$(fetch_token)
  if [ -z "${token:-}" ]; then
    echo "kiro_otel --check: FAIL — no CloudWatch metrics token (aws sso login?)" >&2
    return 1
  fi
  echo "kiro_otel --check: token OK"

  if [ -f "$REPO/.kiro/hooks/.env" ]; then
    echo "kiro_otel --check: .kiro/hooks/.env present"
  else
    echo "kiro_otel --check: WARN — .kiro/hooks/.env missing (run scripts/kiro_otel.sh)" >&2
  fi

  if [ -f "$REPO/.kiro/hooks/otel-forward.json" ]; then
    echo "kiro_otel --check: hook config present at .kiro/hooks/otel-forward.json"
  else
    echo "kiro_otel --check: WARN — missing .kiro/hooks/otel-forward.json" >&2
  fi

  if [ -x "$REPO/.kiro/hooks/forward.sh" ]; then
    echo "kiro_otel --check: forward.sh executable"
  else
    echo "kiro_otel --check: WARN — .kiro/hooks/forward.sh not executable" >&2
  fi
  return 0
}

run_setup() {
  local token
  token=$(fetch_token)
  if [ -z "${token:-}" ]; then
    who=$(aws sts get-caller-identity --query Account --output text 2>/dev/null || echo '<no AWS session>')
    echo "kiro_otel: no CloudWatch metrics token — unreadable as $who" >&2
    echo "kiro_otel: is the AWS session live? (aws sso login)" >&2
    exit 1
  fi

  derive_project_repo
  write_env "$token" "$project" "$repo"

  echo "kiro_otel: metrics → ${A2ALAB_CW_OTLP_METRICS_ENDPOINT:-https://monitoring.us-east-1.amazonaws.com/v1/metrics}" >&2
  echo "kiro_otel: project=$project repo=$repo" >&2
  echo "kiro_otel: .kiro/hooks/.env written" >&2
  echo "kiro_otel: open this repo in Kiro, trigger a session, then:" >&2
  echo "kiro_otel:   scripts/kiro_otel.sh --check" >&2
  echo "kiro_otel:   uv run python scripts/obs_harvest.py coding   # after datapoints land" >&2
}

case "$MODE" in
  --check|check)
    run_check
    ;;
  --help|-h|help)
    sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'
    ;;
  setup|"")
    run_setup
    ;;
  *)
    echo "kiro_otel: unknown argument '$MODE' (try --check or --help)" >&2
    exit 1
    ;;
esac
